# Generated by Django 4.0.3 on 2022-04-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('NFT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_generic_features.nft')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='collected',
        ),
        migrations.AddField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(through='web_generic_features.Collected', to='web_generic_features.nft'),
        ),
        migrations.AddField(
            model_name='collected',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_generic_features.profile'),
        ),
    ]
