# Generated by Django 4.0.3 on 2022-04-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0002_collected_remove_profile_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collected',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
