# Generated by Django 4.0.3 on 2022-04-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0003_alter_collected_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='collection',
            new_name='my_collection',
        ),
    ]
