# Generated by Django 4.0.3 on 2022-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(default=10000),
        ),
    ]
