# Generated by Django 4.0.3 on 2022-04-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0009_alter_collected_options_alter_nft_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_collection',
            new_name='collection',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_generic_features.nft')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_generic_features.profile')),
            ],
        ),
    ]
