# Generated by Django 4.0.3 on 2022-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0012_alter_nft_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
