# Generated by Django 4.0.3 on 2022-05-05 10:54

import DesertTraders.web_generic_features.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0015_alter_collection_cover_image_alter_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(upload_to='nfts/', validators=[DesertTraders.web_generic_features.validators.max_image_size]),
        ),
    ]
