# Generated by Django 4.0.3 on 2022-05-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0016_alter_nft_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collected',
            name='favorite',
        ),
    ]
