# Generated by Django 4.0.3 on 2022-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0017_remove_collected_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=10000),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
