# Generated by Django 4.0.3 on 2022-05-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0018_profile_balance_delete_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_quantity', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('NFT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_generic_features.nft')),
            ],
        ),
    ]
