# Generated by Django 4.0.3 on 2022-05-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0019_nftinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collected',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='collection',
        ),
        migrations.DeleteModel(
            name='NFTInfo',
        ),
    ]
