# Generated by Django 4.0.3 on 2022-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0020_alter_collected_options_remove_profile_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collection',
            field=models.ManyToManyField(through='web_generic_features.Collected', to='web_generic_features.nft'),
        ),
    ]
