# Generated by Django 4.0.3 on 2022-05-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0021_profile_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collection',
        ),
    ]
