# Generated by Django 4.0.3 on 2022-05-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_generic_features', '0022_remove_profile_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={},
        ),
        migrations.RenameField(
            model_name='collected',
            old_name='NFT',
            new_name='nft',
        ),
    ]
